sudo: required

language: python

services:
  - docker

before_install:
  - echo $GCLOUD_KEY | base64 --decode -i > gcloud_key.json
  - gcloud auth activate-service-account $GCLOUD_EMAIL --key-file gcloud_key.json
  - docker info
  - docker build -t asia.gcr.io/test/test_ci .
  - gcloud docker push asia.gcr.io/test/test_ci

script: python -m test
