sudo: required

language: python

services:
  - docker

before_install:
  - docker info
  - docker build -t asia.gcr.io/test/test_ci .
  - echo $GCLOUD_KEY | base64 --decode > gcloud.p12
  - gcloud auth activate-service-account $GCLOUD_EMAIL --key-file gcloud.p12
  - ssh-keygen -f ~/.ssh/google_compute_engine -N ""
  - gcloud docker push asia.gcr.io/test/test_ci

script: python -m test
