sudo: required

language: python

services:
  - docker

before_install:
  - gcloud -v
  - echo $GCLOUD_KEY | base64 --decode -i > ${HOME}/gcloud_key.json
  - gcloud auth activate-service-account $GCLOUD_EMAIL --key-file ${HOME}/gcloud_key.json
  - docker info
  - docker build --cache-from asia.gcr.io/$PROJECT_ID/test_ci -t asia.gcr.io/$PROJECT_ID/test_ci .
  - gcloud docker -- push asia.gcr.io/$PROJECT_ID/test_ci

script: python -m test
