sudo: required

language: python

services:
  - docker

before_install:
  - gcloud -v
  - gcloud config set project $PROJECT_ID
  - echo $GCLOUD_KEY | base64 --decode -i > ${HOME}/gcloud_key.json
  - cut -c-10 ${HOME}/gcloud_key.json
  - gcloud auth activate-service-account $GCLOUD_EMAIL --key-file ${HOME}/gcloud_key.json
  - docker info
  - docker build -t asia.gcr.io/test/test_ci .
  - gcloud docker push asia.gcr.io/test/test_ci

script: python -m test
